
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LLAIZQ = 8;
  public static final int AMPERS = 10;
  public static final int MENOS = 11;
  public static final int PUNTO = 20;
  public static final int LLADER = 9;
  public static final int MAYQU = 14;
  public static final int DIVIDIDO = 27;
  public static final int EXCLA = 15;
  public static final int COMILLS = 26;
  public static final int PARIZQ = 4;
  public static final int PUNCO = 16;
  public static final int DOSPUN = 17;
  public static final int PARDER = 5;
  public static final int OLOGI = 22;
  public static final int INTERRO = 24;
  public static final int TILDE = 25;
  public static final int COMA = 21;
  public static final int PORCEN = 18;
  public static final int ASTERI = 23;
  public static final int EOF = 0;
  public static final int CONJU = 2;
  public static final int MENQU = 13;
  public static final int error = 1;
  public static final int IDENTIFICADOR = 28;
  public static final int CORIZQ = 6;
  public static final int ENTERO = 29;
  public static final int CORDER = 7;
  public static final int GUIBA = 12;
  public static final int MAS = 19;
  public static final int PTCOMA = 3;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "CONJU",
  "PTCOMA",
  "PARIZQ",
  "PARDER",
  "CORIZQ",
  "CORDER",
  "LLAIZQ",
  "LLADER",
  "AMPERS",
  "MENOS",
  "GUIBA",
  "MENQU",
  "MAYQU",
  "EXCLA",
  "PUNCO",
  "DOSPUN",
  "PORCEN",
  "MAS",
  "PUNTO",
  "COMA",
  "OLOGI",
  "ASTERI",
  "INTERRO",
  "TILDE",
  "COMILLS",
  "DIVIDIDO",
  "IDENTIFICADOR",
  "ENTERO"
  };
}

